fix htmlproofer args pt. 2

diff --git a/_dev_/html-proofer b/_dev_/html-proofer
--- a/_dev_/html-proofer
+++ b/_dev_/html-proofer
@@ -1,22 +1,28 @@
 #!/bin/bash
 project_dir="$(dirname "$(dirname "$(realpath "$0")")")"
 
-pushd "$project_dir" >/dev/null
+err() {
+    echo "$1" >&2
+    exit 1
+}
 
+# Verify there's a generated site
+[[ -d "$project_dir/public" ]] || err "Run hugo first to build the site"
+
+pushd "$project_dir" >/dev/null || err "pushd failed"
+
+# Build an HTMLProofer image unless it exists
 docker image inspect htmlproofer &>/dev/null || docker build -t htmlproofer .
 
-rm -rf public && hugo
-
+# Run HTMLProofer
 docker run \
     --rm \
     -v "$project_dir/public/":/site \
-    htmlproofer \
-        /site \
+    htmlproofer /site \
+        --allow_missing_href \
+        --checks=Links,Images,Scripts,Favicon,OpenGraph \
         --disable-external \
-        --ignore-urls '/^mailto:\?body=/' \
-        --check-favicon \
-        --check-opengraph \
-        --check-html \
-        --check-img-http
+        --enforce-https=false \
+        --ignore_empty_mailto
 
-popd >/dev/null
+popd >/dev/null || true
